Fix replay to pass proof bug
jjyr/restricted-sparse-merkle-tree pull request #23
Opened 2021-06-29 13:01 UTC by TheWaWaR

2021-06-30 00:34 UTC, xxuejie commented on src/merkle_proof.rs
> +                        left
I was under the impression that right now, even when one branch(left or right) is none, we are still doing the hashing?

2021-06-30 02:01 UTC, jjyr requested changes

2021-06-30 02:01 UTC, jjyr commented on src/merkle_proof.rs
> -            let (&(mut height, key), &(leaf_index, node)) = tree_buf.iter().next().unwrap();
After the fix, we should do exactly 256 times hashing, so we do not need the `tree_buf` & height in the proof.

2021-06-30 02:01 UTC, jjyr commented on src/merkle_proof.rs
> +    proof: Vec<(u8, H256, H256, Option<H256>)>,
The new `proof` is `Vec<H256>`, since we should do exactly 256 times hashing, we do not need to save height in the proof.

2021-07-01 09:56 UTC, TheWaWaR commented on src/merkle_proof.rs
> +                        left
Yes. Only if left/right both are zero we don't do hash.

2021-07-02 06:39 UTC, jjyr commented
https://github.com/nervosnetwork/sparse-merkle-tree/pulls

2021-07-02 06:39 UTC, closed without merging

2021-07-02 06:44 UTC, TheWaWaR commented
https://github.com/nervosnetwork/sparse-merkle-tree/pull/1